{
  "was": {
    "image": {
      "repository": ""
    },
    "logLevel": "INFO"
  },
  "database": {
    "secret": "",
    "urlKey": "DATABASE_URL",
    "caConfigMap": "",
    "caKey": "ca-bundle.pem"
  },
  "api": {
    "digest": "",
    "replicas": 1,
    "host": "",
    "resources": {
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    }
  },
  "buildWorker": {
    "digest": "",
    "replicas": 1,
    "codebuildProject": "",
    "artifactBucket": "",
    "githubSecret": "",
    "resources": {
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    },
    "terminationGracePeriodSeconds": 120
  },
  "deployWorker": {
    "digest": "",
    "replicas": 1,
    "baseDomain": "",
    "gitopsRepository": "2026-softbank-1/iris-gitops-environments",
    "githubSecret": "",
    "argocdUrl": "",
    "argocdSecret": "",
    "caConfigMap": "",
    "caKey": "ca-bundle.pem",
    "resources": {
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    },
    "terminationGracePeriodSeconds": 60
  },
  "errorAgent": {
    "enabled": false,
    "image": {
      "repository": "",
      "digest": ""
    },
    "secret": "",
    "model": "",
    "resources": {
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    }
  },
  "migration": {
    "resources": {
      "requests": {
        "cpu": "100m",
        "memory": "256Mi"
      },
      "limits": {
        "cpu": "500m",
        "memory": "512Mi"
      }
    },
    "activeDeadlineSeconds": 600,
    "backoffLimit": 1
  },
  "network": {
    "albSubnetCidrs": [],
    "rdsSubnetCidrs": []
  },
  "awsRegion": "ap-northeast-2"
}
