apiVersion: v1
kind: ConfigMap
metadata:
  name: iris-onprem-probe
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: iris-onprem-probe
data:
  serverKey: {{ .Values.serverKey | quote }}
