gateway:
  addressName: ""
  certificateMap: ""
  baseDomain: gcp.likelion.uk
credentials:
  enabled: false
  image: ""
  serviceAccountEmail: ""
  serviceAccountId: ""
  awsAccountId: ""
  roleArn: ""
  audience: iris-gcp-ecr-pull
  kubeApiCidr: ""
