{
  "repoURL": "https://github.com/2026-softbank-1/iris-infra.git",
  "revision": "",
  "targets": {},
  "services": {
    "repoURL": "https://github.com/2026-softbank-1/iris-gitops-environments.git",
    "revision": "main",
    "chartRevision": "iris-service-0.4.0"
  },
  "platform": {
    "repos": [
      "was",
      "code-analyzer-agent",
      "error-check-agent"
    ]
  }
}
