apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes.yaml
- all-services.yaml
configMapGenerator:
- name: iris-onprem-auth-renewal-code
  namespace: iris-platform
  files:
  - refresh.py
  - all_services.py
  - server-ca.crt
- name: iris-onprem-auth-renewal-code
  namespace: argocd
  files:
  - refresh.py
  - all_services.py
  - server-ca.crt
